LOAD DATA INFILE 'Pokemon.csv'
INTO TABLE Pokemon(name,HP,sex,height)
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES;

LOAD DATA INFILE 'Type.csv'
INTO TABLE Type(name)
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES;

LOAD DATA INFILE 'Ability.csv'
INTO TABLE Ability(name,description)
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES;

LOAD DATA INFILE 'HasType.csv'
INTO TABLE HasType(pokemonName,typeName)
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES;

LOAD DATA INFILE 'Strengths.csv'
INTO TABLE Strengths(typeName,strongAgainst,multiplier)
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES;

LOAD DATA INFILE 'HasAbility.csv'
INTO TABLE HasAbility(pokemonName,abilityName)
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES;

